language: node_js
node_js:
- lts/*
before_script:
- npm install -g node-red
branches:
  only:
  - master
  - "/([0-9]+\\.){2}[0-9]+/"
before_deploy:
  - "./.travis/before_deploy.sh"
deploy:
  provider: npm
  email: andrewhurt@btinternet.com
  api_key:
    secure: ADN7wpE4KM10HcsMGYJvitff47+IeTxCeXckJayhAmWF7s2x0gCdt7igJhh2dPhyZiCLpEqNoHkfETY/NfhtIDx+tcf/7SeuEV8iThvKo+DCJrE+XcVHlLgZ5WerYOs40DwUUzqOEhFkEs5XG64tYns8IQJraJ+JwbmBTg1yaOhomfqroCa9U6a2Nv+ifD9axNyXINj016YatSAIyEOHQdcgH1Bu3cM79u4rcRH5Ic3iz07fdGfjFSruwsXQNR7RBUHUo7u6hoRcprxdTplYiBAwjVEAq4nc4mK+i6pBzn5v/YsmgI29mdPWMI0aJGx2UfnzYhjreRYPVIJSb2c1Va9b6lqNBwrcA/HVXAO6Zu6uDs+Fsl+rPSCGzrtiXjrgMF4YAOvE08srB48rG9u4u73lrOFrPnlPOoTVwG1cxuq0k1oyP12sUY+t0doVRtSSHl20VQbbKjsTDGrPk5MH4b3EQbmvX1HMi6xwnEynX3/YWzw5sBYYOapC+eYfSoTJ4ldZKg6heMCX/hUWWhSO8aYH94WkQwpLJt6hG3HuNCv2MXvur58Vq3NdxPDnVdjsofVelFG1bUPuPBKHQSu4ySpGE05aaMArdOJ76gy7yimFVWSiraBVWlNe8hPnTk5y/dvrFi5bvbXfONcDQTcK7opSIgGNJiKiWr3o1zzojbA=
  skip_cleanup: true
  on:
    tags: true
    repo: awjh/node-red-contrib-alexa-endpoint
after_deploy:
  - "./.travis/after_deploy.sh"
notifications:
  email:
    on_success: never
    on_failure: never
env:
  global:
    secure: epF44wlKySl2wD2sWK/m9ahkmQdH7H3jPRRy+13Mwx0ocEWIEIvm1twYZchuW/Hjvc0yZEVG5O3YEOTOUhBgXaSqTT1P4W1waKdlHSckdBJa+l/4CxwaKHxcpciio07gcwXMbDOET67RPTb3O7oCJSu9TCR3LW7wI2LdSV1fQ9oEZFXk7gC4ik39bKz6U7A3Oie5+/PeLrJzP0BYxSZ9AT743RIhlYS1GiepR32P6mbnexuHYYVS3kLTA7vUDX7dmGkp/6L5B+x0Pijy27WqjI5p3hBPoUNZ+Tmy80mz8BRF9OaZ2srIA/V5kx9lFBAq1hkrJgxWUVhbtnkTdubjW4KaCjaneuyKhhooNr76I0sqYgShOQPVjJeIuA/kJGuMdCnbrtazUI036vWEISFRXGKv/dVeGLETNHwhr28TDhBQF/KY24dWCnZuXJy4kS9yyHgo0y2e8oWQAK5bC6PDsFPYXWV/WqKRmfRw51X+Y++oYC8GHWPYO06LAFNEj1NVLE34mD7JZI7ckoK/sYazJVlP5EDMxZDMMoLa1TZHmLsJLog9fevL70dz2NNQQbNbIjQFZQE/C6fAm4az3a5f04PRtEAKntciqQIo2clm0krBE1I0yvDUJuT+9YfVF8ouAFb3b5AmyyyOtrxyKIMHj4SXHq8C0bTdQuc20ggZmrU=
